apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: openshift-ingress
spec:
  commonName: apps.plaid.phalnet.com
  dnsNames:
  - 'apps.plaid.phalnet.com'
  - '*.apps.plaid.phalnet.com'
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: custom-certs-managed
